name: workout-planner-app

services:
  composite-service:
    build: microservices/composite-service
    mem_limit: 512m
    ports:
      - 8080:8080

  user:
    build: microservices/user
    mem_limit: 512m

  workout:
    build: microservices/workout
    mem_limit: 512m

  mongodb:
    image: mongo:6.0.4
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod