name: workout-planner-app

services:
  user:
    build: microservices/user
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  workout:
    build: microservices/workout
    mem_limit: 512m
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  mongodb:
    image: mongo:6.0.4
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod